FROM node
RUN mkdir -p /usr/src/recruitment-app
RUN mkdir -p /usr/src/recruitment-app/frontend
WORKDIR /usr/src/recruitment-app/frontend
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD [ "npm","run" ,"docker:start" ]