# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    container_name: task-mysql
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: recruitment_database

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: task-frontend
    restart: always
    links:
      - backend
  backend:
    depends_on:
      - db
    build: ./backend
    ports:
      - "5000:5000"
    container_name: task-backend
    restart: always
    links:
      - db
