# Use root/example as user/password credentials
version: "3.1"

services:
  frontend:
    #   Create frontend container
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: task-frontend
    restart: always
    links:
      - backend
  backend:
    # Create backend container
    build: ./backend
    ports:
      - "5000:5000"
    container_name: task-backend
    restart: always
    links:
      - db
  #   Create database container
  db:
    container_name: task-mysql
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recruitment_database