# Base image
FROM node
# Make folder to put our files in
RUN mkdir -p /usr/src/recruitment-app
RUN mkdir -p /usr/src/ecruitment-app/backend
# Set working directory so that all subsequent command runs in this folder
WORKDIR /usr/src/recruitment-app/backend
# Copy package json and install dependencies
COPY package*.json ./
RUN npm install
# Copy our app
COPY . .
# Expose port to access server
ENV NODE_ENV=test
EXPOSE 5000
# Command to run our app
CMD [ "npm", "run" ,"dev"]