# Base image
FROM node
# Make folder to put our files in
RUN mkdir -p /usr/src/recruitment-app
RUN mkdir -p /usr/src/ecruitment-app/backend
# Set working directory so that all subsequent command runs in this folder
WORKDIR /usr/src/recruitment-app/backend
# Copy package json and install dependencies
COPY package*.json ./
RUN npm install
# Copy app
COPY . .
# Expose port to access server
EXPOSE 5000
# Mysql container is exposed on port 3306
ENV DATABASE_URL "mysql://test:test@db:3306"
# Command to run our app
CMD [ "npm", "run" ,"dev"]